name: CI/CD Vue y Cypress

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas de Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:8080'
          browser: chrome

      - name: Compilar proyecto
        run: npm run build

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist